CREATE TABLE [Fj_servindustrias].[fa_tarifario_facturacion_x_cliente] (
    [IdEmpresa]                        INT           NOT NULL,
    [IdTarifario]                      NUMERIC (18)  NOT NULL,
    [IdCliente]                        NUMERIC (18)  NOT NULL,
    [IdEstadoVigencia_cat]             VARCHAR (15)  NULL,
    [codTarifario]                     VARCHAR (50)  NOT NULL,
    [nom_tarifario]                    VARCHAR (50)  NOT NULL,
    [observacion]                      VARCHAR (250) NOT NULL,
    [fecha]                            DATETIME      NOT NULL,
    [fecha_inicio]                     DATETIME      NOT NULL,
    [fecha_fin]                        DATETIME      NOT NULL,
    [Movilizacion]                     FLOAT (53)    NOT NULL,
    [se_fact_depreciacion]             BIT           NOT NULL,
    [se_fact_seguro]                   BIT           NOT NULL,
    [se_fact_movilizacion]             BIT           NOT NULL,
    [se_fact_gatos]                    BIT           NOT NULL,
    [se_fact_egreso_bodega]            BIT           NOT NULL,
    [se_factura_gastos_roles]          BIT           NOT NULL,
    [se_fact_margen_ganacia]           BIT           NOT NULL,
    [se_fact_horometro]                BIT           NOT NULL,
    [se_fact_horas_minimas]            BIT           NOT NULL,
    [se_fact_otros]                    BIT           NOT NULL,
    [se_fact_recargo_interes]          BIT           NULL,
    [Porcentaje_recargo_iteres_poliza] FLOAT (53)    NULL,
    [IdUsuario]                        VARCHAR (20)  NULL,
    [Estado]                           VARCHAR (1)   NOT NULL,
    [nom_pc]                           VARCHAR (50)  NULL,
    [ip]                               VARCHAR (25)  NULL,
    [IdUsuarioUltMod]                  VARCHAR (20)  NULL,
    [FechaUltMod]                      DATE          NULL,
    [IdUsuarioUltAnu]                  VARCHAR (25)  NULL,
    [Fecha_UltAnu]                     DATE          NULL,
    [MotiAnula]                        VARCHAR (100) NULL,
    CONSTRAINT [PK_fa_contrato_facturacion_x_cliente] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdTarifario] ASC)
);

