//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.FJ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesInventario_FJ_Rpt : DbContext
    {
        public EntitiesInventario_FJ_Rpt()
            : base("name=EntitiesInventario_FJ_Rpt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwINV_FJ_Rpt005> vwINV_FJ_Rpt005 { get; set; }
        public DbSet<vwINV_FJ_Rpt002> vwINV_FJ_Rpt002 { get; set; }
        public DbSet<vwINV_FJ_Rpt003> vwINV_FJ_Rpt003 { get; set; }
        public DbSet<vwINV_FJ_Rpt004> vwINV_FJ_Rpt004 { get; set; }
        public DbSet<vwINV_FJ_Rpt006> vwINV_FJ_Rpt006 { get; set; }
        public DbSet<vwINV_FJ_Rpt001> vwINV_FJ_Rpt001 { get; set; }
        public DbSet<vwINV_FJ_Rpt007> vwINV_FJ_Rpt007 { get; set; }
        public DbSet<vwINV_FJ_Rpt008> vwINV_FJ_Rpt008 { get; set; }
    
        public virtual ObjectResult<spINV_FJ_Rpt003_Result> spINV_FJ_Rpt003(Nullable<int> idEmpresa, Nullable<int> idSucursalIni, Nullable<int> idSucursalFin, Nullable<int> idBodegaIni, Nullable<int> idBodegaFin, Nullable<decimal> idProductoIni, Nullable<decimal> idProductoFin, Nullable<System.DateTime> fechaCorteIni, string idCentro_Costo, string idSubcentro_Costo)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var idSucursalIniParameter = idSucursalIni.HasValue ?
                new ObjectParameter("IdSucursalIni", idSucursalIni) :
                new ObjectParameter("IdSucursalIni", typeof(int));
    
            var idSucursalFinParameter = idSucursalFin.HasValue ?
                new ObjectParameter("IdSucursalFin", idSucursalFin) :
                new ObjectParameter("IdSucursalFin", typeof(int));
    
            var idBodegaIniParameter = idBodegaIni.HasValue ?
                new ObjectParameter("IdBodegaIni", idBodegaIni) :
                new ObjectParameter("IdBodegaIni", typeof(int));
    
            var idBodegaFinParameter = idBodegaFin.HasValue ?
                new ObjectParameter("IdBodegaFin", idBodegaFin) :
                new ObjectParameter("IdBodegaFin", typeof(int));
    
            var idProductoIniParameter = idProductoIni.HasValue ?
                new ObjectParameter("IdProductoIni", idProductoIni) :
                new ObjectParameter("IdProductoIni", typeof(decimal));
    
            var idProductoFinParameter = idProductoFin.HasValue ?
                new ObjectParameter("IdProductoFin", idProductoFin) :
                new ObjectParameter("IdProductoFin", typeof(decimal));
    
            var fechaCorteIniParameter = fechaCorteIni.HasValue ?
                new ObjectParameter("FechaCorteIni", fechaCorteIni) :
                new ObjectParameter("FechaCorteIni", typeof(System.DateTime));
    
            var idCentro_CostoParameter = idCentro_Costo != null ?
                new ObjectParameter("IdCentro_Costo", idCentro_Costo) :
                new ObjectParameter("IdCentro_Costo", typeof(string));
    
            var idSubcentro_CostoParameter = idSubcentro_Costo != null ?
                new ObjectParameter("IdSubcentro_Costo", idSubcentro_Costo) :
                new ObjectParameter("IdSubcentro_Costo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_FJ_Rpt003_Result>("spINV_FJ_Rpt003", idEmpresaParameter, idSucursalIniParameter, idSucursalFinParameter, idBodegaIniParameter, idBodegaFinParameter, idProductoIniParameter, idProductoFinParameter, fechaCorteIniParameter, idCentro_CostoParameter, idSubcentro_CostoParameter);
        }
    
        public virtual ObjectResult<spINV_FJ_Rpt002_Result> spINV_FJ_Rpt002(Nullable<int> idEmpresa, Nullable<int> idSucursalIni, Nullable<int> idSucursalFin, Nullable<int> idBodegaIni, Nullable<int> idBodegaFin, Nullable<decimal> idProductoIni, Nullable<decimal> idProductoFin, Nullable<System.DateTime> fechaCorteIni, string idCentro_costo, string idSubCentro_costo)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var idSucursalIniParameter = idSucursalIni.HasValue ?
                new ObjectParameter("IdSucursalIni", idSucursalIni) :
                new ObjectParameter("IdSucursalIni", typeof(int));
    
            var idSucursalFinParameter = idSucursalFin.HasValue ?
                new ObjectParameter("IdSucursalFin", idSucursalFin) :
                new ObjectParameter("IdSucursalFin", typeof(int));
    
            var idBodegaIniParameter = idBodegaIni.HasValue ?
                new ObjectParameter("IdBodegaIni", idBodegaIni) :
                new ObjectParameter("IdBodegaIni", typeof(int));
    
            var idBodegaFinParameter = idBodegaFin.HasValue ?
                new ObjectParameter("IdBodegaFin", idBodegaFin) :
                new ObjectParameter("IdBodegaFin", typeof(int));
    
            var idProductoIniParameter = idProductoIni.HasValue ?
                new ObjectParameter("IdProductoIni", idProductoIni) :
                new ObjectParameter("IdProductoIni", typeof(decimal));
    
            var idProductoFinParameter = idProductoFin.HasValue ?
                new ObjectParameter("IdProductoFin", idProductoFin) :
                new ObjectParameter("IdProductoFin", typeof(decimal));
    
            var fechaCorteIniParameter = fechaCorteIni.HasValue ?
                new ObjectParameter("FechaCorteIni", fechaCorteIni) :
                new ObjectParameter("FechaCorteIni", typeof(System.DateTime));
    
            var idCentro_costoParameter = idCentro_costo != null ?
                new ObjectParameter("IdCentro_costo", idCentro_costo) :
                new ObjectParameter("IdCentro_costo", typeof(string));
    
            var idSubCentro_costoParameter = idSubCentro_costo != null ?
                new ObjectParameter("IdSubCentro_costo", idSubCentro_costo) :
                new ObjectParameter("IdSubCentro_costo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_FJ_Rpt002_Result>("spINV_FJ_Rpt002", idEmpresaParameter, idSucursalIniParameter, idSucursalFinParameter, idBodegaIniParameter, idBodegaFinParameter, idProductoIniParameter, idProductoFinParameter, fechaCorteIniParameter, idCentro_costoParameter, idSubCentro_costoParameter);
        }
    }
}
