//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_Archivo_Transferencia_Parametros
    {
        public int IdEmpresa { get; set; }
        public int IdBanco { get; set; }
        public string cod_banco { get; set; }
    }
}
