//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_Cbte_Ban_Datos_Entrega_cheq
    {
        public int IdEmpresa { get; set; }
        public decimal IdCbteCble { get; set; }
        public int IdTipocbte { get; set; }
        public System.DateTime fecha_hora_entrega { get; set; }
        public string IdEstado_cheque_cat { get; set; }
        public decimal IdPersona_Entrega { get; set; }
        public string Nota_entrega { get; set; }
        public System.DateTime fecha_trans { get; set; }
        public string usuario { get; set; }
    
        public virtual ba_Catalogo ba_Catalogo { get; set; }
        public virtual ba_Cbte_Ban ba_Cbte_Ban { get; set; }
    }
}
