//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_Config_Diseno_Cheque
    {
        public int IdEmpresa { get; set; }
        public int IdBanco { get; set; }
        public int Tama_Cheque_X { get; set; }
        public int Tama_Cheque_Y { get; set; }
        public int Area_Imprimir_X { get; set; }
        public int Area_Imprimir_Y { get; set; }
        public int PagueseA_X { get; set; }
        public int PagueseA_Y { get; set; }
        public int ValorCheque_X { get; set; }
        public int ValorCheque_Y { get; set; }
        public int ValorLetra_Cheque_X { get; set; }
        public int ValorLetra_Cheque_Y { get; set; }
        public int Fecha_X { get; set; }
        public int Fecha_Y { get; set; }
        public string Nom_Impresora { get; set; }
        public string Pto_Impresora { get; set; }
    
        public virtual ba_Banco_Cuenta ba_Banco_Cuenta { get; set; }
    }
}
