//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_Cbte_Ban_tipo_x_CodBancoExterno
    {
        public string CodTipoCbteBan { get; set; }
        public string CodBanco { get; set; }
    
        public virtual ba_Cbte_Ban_tipo ba_Cbte_Ban_tipo { get; set; }
    }
}
