//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_Cbte_Ban_tipo
    {
        public ba_Cbte_Ban_tipo()
        {
            this.ba_Cbte_Ban_tipo_x_CodBancoExterno = new HashSet<ba_Cbte_Ban_tipo_x_CodBancoExterno>();
            this.ba_Cbte_Ban_tipo_x_ct_CbteCble_tipo = new HashSet<ba_Cbte_Ban_tipo_x_ct_CbteCble_tipo>();
        }
    
        public string CodTipoCbteBan { get; set; }
        public string Descripcion { get; set; }
        public string Signo { get; set; }
        public int orden { get; set; }
    
        public virtual ICollection<ba_Cbte_Ban_tipo_x_CodBancoExterno> ba_Cbte_Ban_tipo_x_CodBancoExterno { get; set; }
        public virtual ICollection<ba_Cbte_Ban_tipo_x_ct_CbteCble_tipo> ba_Cbte_Ban_tipo_x_ct_CbteCble_tipo { get; set; }
    }
}
