//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_comprador_familia
    {
        public int IdEmpresa { get; set; }
        public decimal IdComprador { get; set; }
        public int Secuencia { get; set; }
        public int IdFamilia { get; set; }
    
        public virtual com_comprador com_comprador { get; set; }
    }
}
