//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_solicitante_x_com_departamento
    {
        public int IdEmpresa { get; set; }
        public decimal IdSolicitante { get; set; }
        public int Secuencia { get; set; }
        public decimal IdDepartamento { get; set; }
    
        public virtual com_departamento com_departamento { get; set; }
        public virtual com_solicitante com_solicitante { get; set; }
    }
}
