//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_solicitante_x_com_departamento
    {
        public int IdEmpresa { get; set; }
        public decimal IdSolicitante { get; set; }
        public int Secuencia { get; set; }
        public decimal IdDepartamento { get; set; }
    
        public virtual com_departamento com_departamento { get; set; }
        public virtual com_solicitante com_solicitante { get; set; }
    }
}
