//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_OrdenPedidoDet
    {
        public com_OrdenPedidoDet()
        {
            this.com_CotizacionPedidoDet = new HashSet<com_CotizacionPedidoDet>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdOrdenPedido { get; set; }
        public int Secuencia { get; set; }
        public Nullable<decimal> IdProducto { get; set; }
        public string pr_descripcion { get; set; }
        public string IdUnidadMedida { get; set; }
        public int IdSucursalOrigen { get; set; }
        public int IdSucursalDestino { get; set; }
        public Nullable<int> IdPunto_cargo { get; set; }
        public double opd_Cantidad { get; set; }
        public double opd_CantidadApro { get; set; }
        public string opd_EstadoProceso { get; set; }
        public string opd_Detalle { get; set; }
        public bool Adjunto { get; set; }
        public string NombreArchivo { get; set; }
        public string IdUsuarioCantidad { get; set; }
        public Nullable<System.DateTime> FechaCantidad { get; set; }
        public string IdUsuarioCotizacion { get; set; }
        public Nullable<System.DateTime> FechaCotizacion { get; set; }
        public Nullable<decimal> IdOrdenPedidoReg { get; set; }
        public Nullable<int> SecuenciaReg { get; set; }
        public Nullable<System.DateTime> FechaRef { get; set; }
        public string IdUsuarioReg { get; set; }
    
        public virtual com_OrdenPedido com_OrdenPedido { get; set; }
        public virtual ICollection<com_CotizacionPedidoDet> com_CotizacionPedidoDet { get; set; }
    }
}
