//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_CotizacionPedido
    {
        public com_CotizacionPedido()
        {
            this.com_CotizacionPedidoDet = new HashSet<com_CotizacionPedidoDet>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdCotizacion { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdProveedor { get; set; }
        public string IdTerminoPago { get; set; }
        public System.DateTime cp_Fecha { get; set; }
        public int cp_Plazo { get; set; }
        public int cp_PlazoEntrega { get; set; }
        public string cp_Observacion { get; set; }
        public string cp_ObservacionAdicional { get; set; }
        public decimal IdComprador { get; set; }
        public decimal IdSolicitante { get; set; }
        public decimal IdDepartamento { get; set; }
        public string EstadoJC { get; set; }
        public string EstadoGA { get; set; }
        public Nullable<int> oc_IdOrdenCompra { get; set; }
        public string IdUsuarioJC { get; set; }
        public Nullable<System.DateTime> FechaJC { get; set; }
        public Nullable<decimal> IdOrdenPedido { get; set; }
        public string IdUsuarioCotizacion { get; set; }
        public Nullable<System.DateTime> FechaCotizacion { get; set; }
    
        public virtual com_departamento com_departamento { get; set; }
        public virtual com_TerminoPago com_TerminoPago { get; set; }
        public virtual ICollection<com_CotizacionPedidoDet> com_CotizacionPedidoDet { get; set; }
    }
}
