//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_comprador
    {
        public com_comprador()
        {
            this.com_comprador_familia = new HashSet<com_comprador_familia>();
            this.com_ordencompra_local = new HashSet<com_ordencompra_local>();
            this.com_ConvenioPreciosPorProducto = new HashSet<com_ConvenioPreciosPorProducto>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdComprador { get; set; }
        public string IdUsuario_com { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public string Correo { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string MotiAnula { get; set; }
    
        public virtual ICollection<com_comprador_familia> com_comprador_familia { get; set; }
        public virtual ICollection<com_ordencompra_local> com_ordencompra_local { get; set; }
        public virtual ICollection<com_ConvenioPreciosPorProducto> com_ConvenioPreciosPorProducto { get; set; }
    }
}
