//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_OrdenPedidoPlantilla
    {
        public com_OrdenPedidoPlantilla()
        {
            this.com_OrdenPedidoPlantillaDet = new HashSet<com_OrdenPedidoPlantillaDet>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdPlantilla { get; set; }
        public string op_Codigo { get; set; }
        public string op_Observacion { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> IdPunto_cargo { get; set; }
        public string IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string IdUsuarioUltModi { get; set; }
        public Nullable<System.DateTime> FechaUltModi { get; set; }
        public string IdUsuarioAnu { get; set; }
        public Nullable<System.DateTime> FechaUltAnu { get; set; }
        public string MotivoAnu { get; set; }
        public Nullable<bool> EsCompraUrgente { get; set; }
    
        public virtual ICollection<com_OrdenPedidoPlantillaDet> com_OrdenPedidoPlantillaDet { get; set; }
    }
}
