//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_OrdenPedido
    {
        public com_OrdenPedido()
        {
            this.com_OrdenPedidoDet = new HashSet<com_OrdenPedidoDet>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdOrdenPedido { get; set; }
        public string op_Codigo { get; set; }
        public System.DateTime op_Fecha { get; set; }
        public string op_Observacion { get; set; }
        public decimal IdDepartamento { get; set; }
        public decimal IdSolicitante { get; set; }
        public string IdCatalogoEstado { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> IdPunto_cargo { get; set; }
        public string IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string IdUsuarioUltModi { get; set; }
        public Nullable<System.DateTime> FechaUltModi { get; set; }
        public string IdUsuarioAnu { get; set; }
        public Nullable<System.DateTime> FechaUltAnu { get; set; }
        public string MotivoAnu { get; set; }
        public Nullable<bool> EsCompraUrgente { get; set; }
        public string ObservacionGA { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string IdUsuarioAprobacion { get; set; }
        public Nullable<decimal> IdOrdenPedidoReg { get; set; }
        public string IdUsuarioReg { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
    
        public virtual com_catalogo com_catalogo { get; set; }
        public virtual com_departamento com_departamento { get; set; }
        public virtual com_solicitante com_solicitante { get; set; }
        public virtual ICollection<com_OrdenPedidoDet> com_OrdenPedidoDet { get; set; }
    }
}
