//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_comprador_familia
    {
        public int IdEmpresa { get; set; }
        public decimal IdComprador { get; set; }
        public int Secuencia { get; set; }
        public int IdFamilia { get; set; }
    
        public virtual com_comprador com_comprador { get; set; }
    }
}
