//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_OrdenPedido
    {
        public com_OrdenPedido()
        {
            this.com_OrdenPedidoDet = new HashSet<com_OrdenPedidoDet>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdOrdenPedido { get; set; }
        public string op_Codigo { get; set; }
        public System.DateTime op_Fecha { get; set; }
        public string op_Observacion { get; set; }
        public decimal IdDepartamento { get; set; }
        public decimal IdSolicitante { get; set; }
        public string IdCatalogoEstado { get; set; }
        public bool Estado { get; set; }
        public string IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string IdUsuarioUltModi { get; set; }
        public Nullable<System.DateTime> FechaUltModi { get; set; }
        public string IdUsuarioAnu { get; set; }
        public Nullable<System.DateTime> FechaUltAnu { get; set; }
        public string MotivoAnu { get; set; }
    
        public virtual com_catalogo com_catalogo { get; set; }
        public virtual com_departamento com_departamento { get; set; }
        public virtual com_solicitante com_solicitante { get; set; }
        public virtual ICollection<com_OrdenPedidoDet> com_OrdenPedidoDet { get; set; }
    }
}
