//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_XML_DocumentoDet
    {
        public int IdEmpresa { get; set; }
        public decimal IdDocumento { get; set; }
        public int Secuencia { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> PorcentajeIVA { get; set; }
        public Nullable<double> ValorIva { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual cp_XML_Documento cp_XML_Documento { get; set; }
    }
}
