//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_XML_DocumentoRetAnulado
    {
        public cp_XML_DocumentoRetAnulado()
        {
            this.cp_XML_DocumentoRetAnuladoDet = new HashSet<cp_XML_DocumentoRetAnuladoDet>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdDocumento { get; set; }
        public int SecuenciaAnu { get; set; }
        public string Comprobante { get; set; }
        public string emi_Ruc { get; set; }
        public string emi_RazonSocial { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string ret_CodDocumentoTipo { get; set; }
        public string ret_Establecimiento { get; set; }
        public string ret_PuntoEmision { get; set; }
        public string ret_NumeroDocumento { get; set; }
        public Nullable<System.DateTime> ret_Fecha { get; set; }
        public Nullable<System.DateTime> ret_FechaAutorizacion { get; set; }
        public string ret_NumeroAutorizacion { get; set; }
        public string IdUsuarioAnulacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
    
        public virtual ICollection<cp_XML_DocumentoRetAnuladoDet> cp_XML_DocumentoRetAnuladoDet { get; set; }
    }
}
