//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_XML_Documento
    {
        public int IdEmpresa { get; set; }
        public decimal IdDocumento { get; set; }
        public string XML { get; set; }
        public string Tipo { get; set; }
        public string emi_RazonSocial { get; set; }
        public string emi_NombreComercial { get; set; }
        public string emi_Ruc { get; set; }
        public string emi_DireccionMatriz { get; set; }
        public string ClaveAcceso { get; set; }
        public string CodDocumento { get; set; }
        public string Establecimiento { get; set; }
        public string PuntoEmision { get; set; }
        public string NumeroDocumento { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public string rec_RazonSocial { get; set; }
        public string rec_Identificacion { get; set; }
        public Nullable<double> Subtotal0 { get; set; }
        public Nullable<double> SubtotalIVA { get; set; }
        public Nullable<double> Porcentaje { get; set; }
        public Nullable<double> ValorIVA { get; set; }
        public Nullable<double> Total { get; set; }
        public string FormaPago { get; set; }
        public Nullable<int> Plazo { get; set; }
    }
}
