//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_spCONTA_Rpt023
    {
        public int IdEmpresa { get; set; }
        public string IdCtaCble { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdUsuario { get; set; }
        public string IdCtaCblePadre { get; set; }
        public string Naturaleza { get; set; }
        public string NombreCuenta { get; set; }
        public string NombreCentroCosto { get; set; }
        public bool EsCuentaMovimiento { get; set; }
        public int NivelCuenta { get; set; }
        public decimal Saldo { get; set; }
        public decimal SaldoNaturaleza { get; set; }
    }
}
