//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_Familia
    {
        public in_Familia()
        {
            this.in_Producto = new HashSet<in_Producto>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdFamilia { get; set; }
        public string fa_Codigo { get; set; }
        public string fa_Descripcion { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<in_Producto> in_Producto { get; set; }
    }
}
