//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_transferencia
    {
        public in_transferencia()
        {
            this.in_transferencia_x_fa_guia_remision = new HashSet<in_transferencia_x_fa_guia_remision>();
            this.in_transferencia_x_in_Guia_x_traspaso_bodega = new HashSet<in_transferencia_x_in_Guia_x_traspaso_bodega>();
            this.in_transferencia_det = new HashSet<in_transferencia_det>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdSucursalOrigen { get; set; }
        public int IdBodegaOrigen { get; set; }
        public decimal IdTransferencia { get; set; }
        public string Codigo { get; set; }
        public int IdSucursalDest { get; set; }
        public int IdBodegaDest { get; set; }
        public string tr_Observacion { get; set; }
        public System.DateTime tr_fecha { get; set; }
        public Nullable<int> IdEmpresa_Ing_Egr_Inven_Origen { get; set; }
        public Nullable<int> IdSucursal_Ing_Egr_Inven_Origen { get; set; }
        public Nullable<int> IdMovi_inven_tipo_SucuOrig { get; set; }
        public Nullable<decimal> IdNumMovi_Ing_Egr_Inven_Origen { get; set; }
        public Nullable<int> IdEmpresa_Ing_Egr_Inven_Destino { get; set; }
        public Nullable<int> IdSucursal_Ing_Egr_Inven_Destino { get; set; }
        public Nullable<int> IdMovi_inven_tipo_SucuDest { get; set; }
        public Nullable<decimal> IdNumMovi_Ing_Egr_Inven_Destino { get; set; }
        public string IdUsuario { get; set; }
        public string Estado { get; set; }
        public string tr_userAnulo { get; set; }
        public Nullable<System.DateTime> tr_fechaAnulacion { get; set; }
        public Nullable<System.DateTime> tr_fecha_transaccion { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string motivo_anula { get; set; }
        public Nullable<decimal> IdGuia { get; set; }
        public string EstadoRevision { get; set; }
        public string IdUsuarioRevision { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public Nullable<bool> TuvoError { get; set; }
    
        public virtual in_Ing_Egr_Inven in_Ing_Egr_Inven { get; set; }
        public virtual in_Ing_Egr_Inven in_Ing_Egr_Inven1 { get; set; }
        public virtual ICollection<in_transferencia_x_fa_guia_remision> in_transferencia_x_fa_guia_remision { get; set; }
        public virtual ICollection<in_transferencia_x_in_Guia_x_traspaso_bodega> in_transferencia_x_in_Guia_x_traspaso_bodega { get; set; }
        public virtual ICollection<in_transferencia_det> in_transferencia_det { get; set; }
    }
}
