//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_mobileSCI : DbContext
    {
        public Entities_mobileSCI()
            : base("name=Entities_mobileSCI")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_bodega> tbl_bodega { get; set; }
        public DbSet<tbl_producto> tbl_producto { get; set; }
        public DbSet<tbl_subcentro> tbl_subcentro { get; set; }
        public DbSet<tbl_usuario> tbl_usuario { get; set; }
        public DbSet<tbl_usuario_x_bodega> tbl_usuario_x_bodega { get; set; }
        public DbSet<tbl_usuario_x_subcentro> tbl_usuario_x_subcentro { get; set; }
    }
}
