//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_mobileSCI : DbContext
    {
        public Entities_mobileSCI()
            : base("name=Entities_mobileSCI")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_bodega> tbl_bodega { get; set; }
        public DbSet<tbl_producto> tbl_producto { get; set; }
        public DbSet<tbl_subcentro> tbl_subcentro { get; set; }
        public DbSet<tbl_usuario> tbl_usuario { get; set; }
        public DbSet<tbl_usuario_x_bodega> tbl_usuario_x_bodega { get; set; }
        public DbSet<tbl_usuario_x_subcentro> tbl_usuario_x_subcentro { get; set; }
        public DbSet<vw_movimientos_det> vw_movimientos_det { get; set; }
        public DbSet<tbl_movimientos_det_apro> tbl_movimientos_det_apro { get; set; }
        public DbSet<vw_movimientos_csv> vw_movimientos_csv { get; set; }
        public DbSet<tbl_movimientos_det> tbl_movimientos_det { get; set; }
        public DbSet<tbl_producto_x_tbl_bodega> tbl_producto_x_tbl_bodega { get; set; }
        public DbSet<vwtbl_producto> vwtbl_producto { get; set; }
        public DbSet<vwtbl_producto_x_tbl_bodega> vwtbl_producto_x_tbl_bodega { get; set; }
    }
}
