//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_Documento_Tipo_Reporte_x_Empresa
    {
        public int IdEmpresa { get; set; }
        public string codDocumentoTipo { get; set; }
        public byte[] File_Disenio_Reporte { get; set; }
    
        public virtual tb_sis_Documento_Tipo tb_sis_Documento_Tipo { get; set; }
    }
}
