//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usuario
    {
        public tbl_usuario()
        {
            this.tbl_usuario_x_bodega = new HashSet<tbl_usuario_x_bodega>();
            this.tbl_usuario_x_subcentro = new HashSet<tbl_usuario_x_subcentro>();
        }
    
        public string IdUsuarioSCI { get; set; }
        public string clave { get; set; }
        public string nom_usuario { get; set; }
        public bool estado { get; set; }
    
        public virtual ICollection<tbl_usuario_x_bodega> tbl_usuario_x_bodega { get; set; }
        public virtual ICollection<tbl_usuario_x_subcentro> tbl_usuario_x_subcentro { get; set; }
    }
}
