//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_movimientos_csv
    {
        public decimal IdSincronizacion { get; set; }
        public int IdSecuencia { get; set; }
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public int IdMovi_inven_tipo { get; set; }
        public decimal IdNumMovi { get; set; }
        public int Secuencia { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public string NomCentroCosto { get; set; }
        public string NomSubCentro { get; set; }
        public string CodProduccionSC { get; set; }
        public string pr_descripcion { get; set; }
        public string CodProduccionPro { get; set; }
        public string Su_Descripcion { get; set; }
        public string bo_Descripcion { get; set; }
        public double Cantidad { get; set; }
        public decimal IdProducto { get; set; }
        public System.DateTime Fecha { get; set; }
        public string IdUnidadMedida { get; set; }
        public double Peso { get; set; }
    }
}
