//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwba_Banco_Estado_Cheques
    {
        public int IdEmpresa { get; set; }
        public string IdEstado_Concil_Cat { get; set; }
        public decimal IdCbteCble { get; set; }
        public bool @checked { get; set; }
        public string Estado_Conciliacion { get; set; }
        public int IdTipocbte { get; set; }
    }
}
