//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwba_TipoFlujo
    {
        public int IdEmpresa { get; set; }
        public decimal IdTipoFlujo { get; set; }
        public string Descricion { get; set; }
        public Nullable<decimal> IdTipoFlujoPadre { get; set; }
        public string DescricionPadre { get; set; }
        public string Estado { get; set; }
        public string Tipo { get; set; }
        public string cod_flujo { get; set; }
    }
}
