//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwba_Archivo_Transferencia_Det_mov_caj_x_cobro
    {
        public long IdRow { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdArchivo { get; set; }
        public int Secuencia { get; set; }
        public int mcj_IdEmpresa { get; set; }
        public int mcj_IdTipocbte { get; set; }
        public decimal mcj_IdCbteCble { get; set; }
        public int mcj_secuencia { get; set; }
        public int cbr_IdEmpresa { get; set; }
        public int cbr_IdSucursal { get; set; }
        public decimal cbr_IdCobro { get; set; }
        public string IdCtaCble { get; set; }
        public double dc_Valor { get; set; }
        public bool Es_CtaCble_caja { get; set; }
        public bool Contabilizado { get; set; }
    }
}
