//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwba_notasDebCre_masivo_consul
    {
        public int IdEmpresa { get; set; }
        public decimal IdTransaccion { get; set; }
        public System.DateTime tm_fecha { get; set; }
        public string tm_observacion { get; set; }
        public string tm_tipo { get; set; }
        public string tm_IdUsuario { get; set; }
        public Nullable<int> TotalTransacciones { get; set; }
    }
}
