//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwba_tipo_nota
    {
        public int IdEmpresa { get; set; }
        public int IdTipoNota { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
        public string IdCtaCble { get; set; }
        public string nom_CtaCble { get; set; }
        public string IdCentroCosto { get; set; }
        public string nom_CentroCosto { get; set; }
        public string Estado { get; set; }
    }
}
