//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwba_prestamo_detalle_cancelacion
    {
        public int IdEmpresa { get; set; }
        public decimal IdPrestamo { get; set; }
        public string IdMotivo_Prestamo { get; set; }
        public string IdMetCalc { get; set; }
        public int NumCuota { get; set; }
        public string EstadoPago { get; set; }
        public string NomEstadoPago { get; set; }
        public double Monto_Canc { get; set; }
        public double Saldo_Canc { get; set; }
        public double TotalCuota { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string Observacion_canc { get; set; }
        public int IdBanco { get; set; }
        public string NomBanco { get; set; }
        public string IdCtaCble_Prestamo { get; set; }
        public string IdCtaCble_Banco { get; set; }
        public double Interes { get; set; }
        public double SaldoInicial { get; set; }
        public double AbonoCapital { get; set; }
        public double Saldo { get; set; }
    }
}
