//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwba_Archivo_Transferencia_x_PreAviso_Cheq_det
    {
        public int IdEmpresa { get; set; }
        public decimal IdArchivo_preaviso_cheq { get; set; }
        public int secuencia { get; set; }
        public string observacion_det { get; set; }
        public int IdEmpresa_mvba { get; set; }
        public decimal IdCbteCble_mvba { get; set; }
        public int IdTipocbte_mvba { get; set; }
        public string CodTipoCbte { get; set; }
        public System.DateTime cb_Fecha { get; set; }
        public string cb_Observacion { get; set; }
        public double cb_Valor { get; set; }
        public string cb_Cheque { get; set; }
        public string cb_giradoA { get; set; }
        public string IdEstado_Preaviso_ch_cat { get; set; }
    }
}
