//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwba_Archivo_Transferencia_x_PreAviso_Cheq
    {
        public int IdEmpresa { get; set; }
        public decimal IdArchivo_preaviso_cheq { get; set; }
        public string cod_Archivo_preaviso_cheq { get; set; }
        public int IdBanco { get; set; }
        public string Nom_Archivo { get; set; }
        public string Observacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Estado { get; set; }
        public System.DateTime Fecha_Proceso { get; set; }
        public byte[] Archivo { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string Nom_pc { get; set; }
        public string Ip { get; set; }
        public string Motivo_anulacion { get; set; }
        public string nom_banco { get; set; }
    }
}
