//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcom_OrdenPedido
    {
        public int IdEmpresa { get; set; }
        public decimal IdOrdenPedido { get; set; }
        public string op_Codigo { get; set; }
        public System.DateTime op_Fecha { get; set; }
        public string op_Observacion { get; set; }
        public string nom_departamento { get; set; }
        public string nom_solicitante { get; set; }
        public bool Estado { get; set; }
        public string IdUsuario { get; set; }
        public string CatalogoEstado { get; set; }
        public string IdCatalogoEstado { get; set; }
        public decimal IdSolicitante { get; set; }
        public decimal IdDepartamento { get; set; }
        public Nullable<bool> EsCompraUrgente { get; set; }
        public string nom_punto_cargo { get; set; }
        public Nullable<int> IdPunto_cargo { get; set; }
        public string ObservacionGA { get; set; }
        public Nullable<decimal> IdOrdenPedidoReg { get; set; }
    }
}
