//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcom_solicitante
    {
        public int IdEmpresa { get; set; }
        public decimal IdSolicitante { get; set; }
        public string nom_solicitante { get; set; }
        public string estado { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<decimal> IdDepartamento { get; set; }
        public string nom_departamento { get; set; }
        public bool ConsultaDepartamento { get; set; }
    }
}
