//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcom_CotizacionPedido
    {
        public int IdEmpresa { get; set; }
        public decimal IdCotizacion { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdProveedor { get; set; }
        public string IdTerminoPago { get; set; }
        public System.DateTime cp_Fecha { get; set; }
        public int cp_Plazo { get; set; }
        public string cp_Observacion { get; set; }
        public decimal IdComprador { get; set; }
        public decimal IdSolicitante { get; set; }
        public decimal IdDepartamento { get; set; }
        public string EstadoJC { get; set; }
        public string EstadoGA { get; set; }
        public string Su_Descripcion { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string TerminoPago { get; set; }
        public string Comprador { get; set; }
        public string nom_solicitante { get; set; }
        public string nom_departamento { get; set; }
        public Nullable<bool> Pasado { get; set; }
        public int cp_PlazoEntrega { get; set; }
        public Nullable<decimal> opd_IdOrdenPedido { get; set; }
        public string cp_ObservacionAdicional { get; set; }
        public Nullable<bool> EsCompraUrgente { get; set; }
    }
}
