//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcom_OrdenPedidoPlantilla
    {
        public int IdEmpresa { get; set; }
        public decimal IdPlantilla { get; set; }
        public string op_Codigo { get; set; }
        public string op_Observacion { get; set; }
        public bool Estado { get; set; }
        public Nullable<bool> EsCompraUrgente { get; set; }
        public string nom_punto_cargo { get; set; }
    }
}
