//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcom_OrdenPedidoPlantilla
    {
        public int IdEmpresa { get; set; }
        public decimal IdPlantilla { get; set; }
        public string op_Codigo { get; set; }
        public string op_Observacion { get; set; }
        public bool Estado { get; set; }
        public Nullable<bool> EsCompraUrgente { get; set; }
        public string nom_punto_cargo { get; set; }
    }
}
