//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcom_solicitante
    {
        public int IdEmpresa { get; set; }
        public decimal IdSolicitante { get; set; }
        public string nom_solicitante { get; set; }
        public string estado { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<decimal> IdDepartamento { get; set; }
        public string nom_departamento { get; set; }
        public bool ConsultaDepartamento { get; set; }
    }
}
