//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.Naturisa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesInventario_Rpt_Natu : DbContext
    {
        public EntitiesInventario_Rpt_Natu()
            : base("name=EntitiesInventario_Rpt_Natu")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwINV_NAT_Rpt002> vwINV_NAT_Rpt002 { get; set; }
        public DbSet<vwINV_NAT_Rpt003> vwINV_NAT_Rpt003 { get; set; }
        public DbSet<vwINV_NAT_Rpt004> vwINV_NAT_Rpt004 { get; set; }
        public DbSet<vwINV_NAT_Rpt005> vwINV_NAT_Rpt005 { get; set; }
        public DbSet<vwINV_NAT_Rpt006> vwINV_NAT_Rpt006 { get; set; }
        public DbSet<vwINV_NAT_Rpt001> vwINV_NAT_Rpt001 { get; set; }
    }
}
