//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.Naturisa
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCOMP_NATU_Rpt004
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdOrdenCompra { get; set; }
        public decimal IdProveedor { get; set; }
        public string Tipo { get; set; }
        public string IdTerminoPago { get; set; }
        public int Plazo { get; set; }
        public System.DateTime Fecha_oc { get; set; }
        public string Observacion_oc { get; set; }
        public string Estado { get; set; }
        public string IdEstadoRecepcion_cat { get; set; }
        public double Total { get; set; }
        public string nom_proveedor { get; set; }
        public string nom_sucursal { get; set; }
        public decimal IdProducto { get; set; }
        public double Cantidad { get; set; }
        public double Precio { get; set; }
        public double Subtotal { get; set; }
        public double Iva { get; set; }
        public string cod_producto { get; set; }
        public string nom_producto { get; set; }
        public string do_observacion { get; set; }
        public string Termino_pago { get; set; }
    }
}
