//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.Naturisa
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCXP_NATU_Rpt004
    {
        public int IdEmpresa { get; set; }
        public decimal IdProveedor { get; set; }
        public string nom_proveedor { get; set; }
        public Nullable<double> Debitos { get; set; }
        public Nullable<double> Creditos { get; set; }
        public Nullable<double> Saldo { get; set; }
        public int IdClaseProveedor { get; set; }
        public string descripcion_clas_prove { get; set; }
    }
}
