//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.Naturisa
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCXP_NATU_Rpt008
    {
        public long fila { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdCbteCble_Ogiro { get; set; }
        public int IdTipoCbte_Ogiro { get; set; }
        public string IdOrden_giro_Tipo { get; set; }
        public decimal IdProveedor { get; set; }
        public System.DateTime co_fechaOg { get; set; }
        public string co_serie { get; set; }
        public string co_factura { get; set; }
        public System.DateTime co_FechaFactura { get; set; }
        public string co_observacion { get; set; }
        public double co_subtotal_iva { get; set; }
        public double co_subtotal_siniva { get; set; }
        public double co_baseImponible { get; set; }
        public double co_Por_iva { get; set; }
        public double co_total { get; set; }
        public double co_valorpagar { get; set; }
        public double Total_Retencion { get; set; }
        public double Total_Pagos { get; set; }
        public double Total_NC { get; set; }
        public Nullable<double> Saldo { get; set; }
        public Nullable<decimal> IdTipoFlujo { get; set; }
        public string IdTipoServicio { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public string nom_proveedor { get; set; }
        public string cod_TipoDocumento { get; set; }
        public string nom_TipoDocumento { get; set; }
        public string nom_TipoFlujo { get; set; }
        public string nom_Sucursal { get; set; }
        public int IdClaseProveedor { get; set; }
        public string nom_claseProveedor { get; set; }
    }
}
