//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.Naturisa
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwINV_NAT_Rpt001
    {
        public int IdEmpresa { get; set; }
        public decimal IdGuia { get; set; }
        public string TipoDetalle { get; set; }
        public int secuencia { get; set; }
        public Nullable<int> IdEmpresa_OC { get; set; }
        public Nullable<int> IdSucursal_OC { get; set; }
        public Nullable<decimal> IdOrdenCompra_OC { get; set; }
        public Nullable<int> Secuencia_OC { get; set; }
        public string observacion { get; set; }
        public Nullable<decimal> IdProducto { get; set; }
        public double Cantidad_enviar { get; set; }
        public string nom_producto { get; set; }
        public Nullable<double> CantOC { get; set; }
        public string Observacion_OC { get; set; }
        public string Num_Fact { get; set; }
        public Nullable<decimal> IdProveedor { get; set; }
        public string nom_proveedor { get; set; }
        public string NumGuia { get; set; }
        public Nullable<int> IdSucursal_Partida { get; set; }
        public string Nom_Sucursal_Partida { get; set; }
        public string Direc_sucu_Partida { get; set; }
        public Nullable<int> IdSucursal_Llegada { get; set; }
        public string Nom_Sucursal_LLegada { get; set; }
        public string Direc_sucu_Llegada { get; set; }
        public Nullable<decimal> IdTransportista { get; set; }
        public string nom_transportista { get; set; }
        public string cedu_transportista { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Fecha_Traslado { get; set; }
        public Nullable<System.DateTime> Fecha_llegada { get; set; }
        public string IdMotivo_Traslado { get; set; }
        public Nullable<System.TimeSpan> Hora_Traslado { get; set; }
        public Nullable<System.TimeSpan> Hora_Llegada { get; set; }
        public string nom_motivo { get; set; }
        public string pr_codigo { get; set; }
        public string Placa { get; set; }
    }
}
