CREATE TABLE [dbo].[com_SPCOM_SeguimientoEntrega] (
    [IdEmpresa]                   INT            NOT NULL,
    [IdUsuario]                   VARCHAR (50)   NOT NULL,
    [IdOrdenPedido]               NUMERIC (18)   NOT NULL,
    [Secuencia]                   INT            NOT NULL,
    [IdProducto]                  NUMERIC (18)   NULL,
    [pr_descripcion]              NVARCHAR (500) NULL,
    [EstadoSolpe]                 VARCHAR (50)   NOT NULL,
    [IdSucursalOrigen]            INT            NOT NULL,
    [CodigoSucOrigen]             VARCHAR (10)   NULL,
    [NombreSucursalOrigen]        NCHAR (60)     NULL,
    [IdSucursalDestino]           INT            NOT NULL,
    [CodigoSucDestino]            VARCHAR (10)   NULL,
    [NombreSucursalDestino]       NCHAR (60)     NULL,
    [EstadoDetalle]               VARCHAR (23)   NULL,
    [nom_solicitante]             VARCHAR (500)  NOT NULL,
    [op_Fecha]                    DATE           NOT NULL,
    [opd_Cantidad]                FLOAT (53)     NOT NULL,
    [opd_CantidadApro]            FLOAT (53)     NOT NULL,
    [IdUsuarioCantidad]           VARCHAR (50)   NULL,
    [FechaCantidad]               DATETIME       NULL,
    [NombreUsuarioCantidad]       VARCHAR (50)   NULL,
    [NomUnidadMedida]             VARCHAR (500)  NULL,
    [op_Observacion]              VARCHAR (MAX)  NULL,
    [ObservacionGA]               VARCHAR (MAX)  NULL,
    [opd_Detalle]                 VARCHAR (MAX)  NULL,
    [IdSucursalOC]                INT            NULL,
    [IdOrdenCompra]               NUMERIC (18)   NULL,
    [SecuenciaOC]                 INT            NULL,
    [IdProveedor]                 NUMERIC (18)   NULL,
    [pe_nombreCompleto]           VARCHAR (200)  NULL,
    [CodigoOC]                    VARCHAR (50)   NULL,
    [CantidadOC]                  FLOAT (53)     NULL,
    [FechaOC]                     DATETIME       NULL,
    [FechaEntrega]                DATETIME       NULL,
    [IdComprador]                 INT            NULL,
    [NombreComprador]             VARCHAR (100)  NULL,
    [IB_UltIdNumMovi]             NUMERIC (18)   NULL,
    [IB_Cantidad]                 FLOAT (53)     NULL,
    [IB_Fecha]                    DATE           NULL,
    [AlertaEntrega]               INT            NULL,
    [CantidadPendiente]           FLOAT (53)     NULL,
    [DiasPendiente]               INT            NULL,
    [NombreSucursalTransferencia] VARCHAR (500)  NULL,
    [NombreBodegaTransferencia]   VARCHAR (500)  NULL,
    [FechaTransferencia]          DATE           NULL,
    [FechaRecepcionTransferencia] DATE           NULL,
    CONSTRAINT [PK_com_SPCOM_SeguimientoEntrega] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdUsuario] ASC, [IdOrdenPedido] ASC, [Secuencia] ASC)
);



