CREATE TABLE [dbo].[XXXAUDITORIARRHHLARVI] (
    [EMPRESA]          INT           NOT NULL,
    [CEDULA]           VARCHAR (20)  NOT NULL,
    [NOMBRETRABAJADOR] VARCHAR (400) NOT NULL,
    [RUBRO]            VARCHAR (300) NOT NULL,
    [VALOR]            FLOAT (53)    NOT NULL,
    [TIPO]             VARCHAR (20)  NOT NULL,
    CONSTRAINT [PK_XXXAUDITORIARRHHLARVI] PRIMARY KEY CLUSTERED ([EMPRESA] ASC, [CEDULA] ASC, [NOMBRETRABAJADOR] ASC, [RUBRO] ASC)
);

