CREATE TABLE [dbo].[XXXAUDITORIARRHH] (
    [EMPRESA]          INT           NOT NULL,
    [CEDULA]           VARCHAR (20)  NOT NULL,
    [NOMBRETRABAJADOR] VARCHAR (500) NOT NULL,
    [RUBRO]            VARCHAR (200) NOT NULL,
    [VALOR]            FLOAT (53)    NOT NULL,
    [TIPO]             VARCHAR (20)  NOT NULL,
    CONSTRAINT [PK_XXXAUDITORIARRHH] PRIMARY KEY CLUSTERED ([EMPRESA] ASC, [CEDULA] ASC, [NOMBRETRABAJADOR] ASC, [RUBRO] ASC)
);

