CREATE TABLE [dbo].[XXXCONSULTACUENTAS] (
    [ID]        NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [IdCtaCble] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_XXXCONSULTACUENTAS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

